services:
  postgres:
    image: postgres:16-alpine
    container_name: onboarding-chatbot-db
    environment:
      POSTGRES_DB: onboarding_chatbot
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: local_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d onboarding_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
